### ISSUE TITLE
 HU.1 Partida Multijugador

### ISSUE THREAD

**Issue by baesparza** [InDevelopmentCompany/Hestia-Project#2]
Yo como estudiante requiero poder competir contra otros estudiantes

**Dependencia**

- HU.2

**Tareas**
- [ ]

**Comment by baesparza** [comment]
# Firebase Data Model

This is a description of the data stored in the Cloud Firestore Database. This also includes, pre-defined types of data, rules, and more information on how to work with the data stored in the Firebase Firestore Database.

## Firebase Firestore

### Academic Areas

This is a catalog of every academic area UTPL has. This collection can be updated by the **admin user**.

**degreesCount update:** The `degreesCount` should match the exact number of `AcademicDegrees` in the AcademicDegrees Collection that relates to this `AcademicArea`. **Must be synchronized!**, automatically increments or decrement every time an academic degree is created or deleted. The initial value is 0.

**description update:** The description is the only field that can be updated by the admin user.

```yaml
Collection: AcademicAreas
    {AcademicArea Document}
        # The id of each area entry should be a raw string of the area name.
        id: <String>

        # Display name of this area
        name: <String>

        # Description or information about this academic area
        description: <String | Null>

        # Degrees that are related to this academic degree
        degrees: <Array<Object>>
            0:
                # Reference to this academic degree
                reference: <DocumentReference<AcademicDegree>>
                
                # Name of the academic degree
                name: <String>
```

### Academic Degrees

This is a catalog of all academic degrees found at https://inscripciones.utpl.edu.ec/presencial, this academic degrees can be after selected by the users as a first and second option for studding at UTPL.

```yaml
Collection: AcademicDegrees
    {AcademicDegree Document}
        # identifies of the degree in raw-format
        id: <String>

        # display name of the academic degree
        name: <String>

        # information about this degree, as a description
        information: <String>

        # Redirect URL to the official site of this degree
        redirectUrl: <String | Null>

        # duration in minutes of the admission test.
        admissionTestDuration: <Number | Null>

        # number of question in the admission test
        numberOfQuestions: <Number | Null>

        # duration in years to obtain the degree.
        degreeDuration: <Number | Null>

        # number of coupons offered
        offeredCoupons: <Number | Null>

        # title of the degree obtained
        degreeTitle: <String | Null>

        # Related information to the academic area this is related to
        area: <Object>
            # Firestore reference to an academic area
            reference: <DocumentReference<AcademicArea>>

            # Name of the area
            name: <String>

        # hero image used for this degree
        image: <Object | Null>
            # Web url of the image
            url: <String>

            # Path to the storage location, if a file was uploaded to the  storage bucket
            path: <String | Null>

            # Width of the image, if provided
            width: <Number | Null>

            # Heigh of the image, if provided
            heigh: <Number | Null>

        # Knowledge areas this degree includes
        knowledgeAreas: <Array<Object>>
            0:
                # Firestore reference to that knowledge Area
                reference: <DocumentReference<KnowledgeArea>>

                # display name of the knowledge area
                name: <String>
```

### Achievvements

```yaml
Collection: Archievements
    {Archievement Document}
        # Archievement identifier
        id: <String>
        
        # Name of the archievement
        name: <String>
        
        # Description of this archievement
        description: <String>
        
        # Image of the archievement
        image: <Object>
            # Web url of the image
            url: <String>

            # Path to the storage location, if a file was uploaded to the  storage bucket
            path: <String | Null>

            # Width of the image, if provided
            width: <Number | Null>

            # Heigh of the image, if provided
            heigh: <Number | Null>
```


### Knowledge Areas, Questions Blocks & Questions

The test is based in knowledge areas, these areas are specified at https://inscripciones.utpl.edu.ec/presencial/pruebaadmision. Each knowledge can have different blocks of questions, also, each block of questions contains the questions.

#### About Questions Blocks

**LeaderBoard:** The leader board will store the top 5 best punctuations. And will be updated every time this question block is answered showing the top 5 best results. To see all the users that have responded this questions block, check the `BlockResponses` collection.

**Enabled Questions:"** is synchronized with the number of **enabled** questions it contains

```yaml
Collection: KnowledgeAreas
    {KnowledgeArea Document}
        # name of the degree in raw string
        id: <String>

        # name of the knowledge area
        name: <String>

        # full description of the knowledge area
        description: <String>

        # list of the content the knowledge area includes
        contentSpecifications: <Array<String>>
            0: <String>

        # Statistics of this knowledge area
        stats: <Object>
            #  number of questions blocks this knowledge area contains
            questionsBlocks: <Number>

        # =======================================================
        # Sub-collection of questions blocks for this knowledge area
        # =======================================================
        Collection: QuestionsBlocks
            {QuestionsBlock Document}
                # identifier of the block
                id: <String>

                # Name of the question block
                name: <String | Null>

                # Date when this question block was created
                dateCreated: <Date>
                
                # Wether the question is playable or not
                enabled: <Boolean>

                # Other data included with the questions block
                referralData: <Object | Null>
                    <String>: <String> 
                    
                # leader board, top 5 users
                leaderBoard: <Array<BlockResponse>>
                    0:
                        # identifier of the response
                        id: <String>

                        # reference to the user document
                        userReference: <DocumentReference<User>>

                        # name of the user
                        name: <String>
                        
                        # avatar of the user
                        avatar: <Object>
                            # Web url of the image
                            url: <String>

                            # Path to the storage location, if a file was uploaded to the  storage bucket
                            path: <String | Null>

                            # Width of the image, if provided
                            width: <Number | Null>

                            # Heigh of the image, if provided
                            heigh: <Number | Null>

                        # points this user obtained in this blockResponse
                        pointsObtained: <Number>

                        # reference to the game played with the history, and selections
                        gameReference: <DocumentReference<GamePlayed>>
                        
                        # date when the user user played this block.
                        date: <Date>

                # stats about this block
                stats: <Object>
                    # number of times this block have been played
                    timesPlayed: <Number>
                    
                    # Number of questions this question block has
                    questions: <Number>

                # =======================================================
                # Sub-collection of questions for each question block
                # =======================================================
                Collection: Questions
                    {Question Document}
                        # identifier of the question
                        id: <String>

                        # how hard is the question
                        difficulty: <QuestionDifficulty>

                        # the main text of the asked question
                        questionText: <String>

                        # number included in the question, also used for sequence,
                        indexingNumber: <Number | Null>

                        # default message to be show in case of wrong answer
                        defaultWrongAnswerMessage: <String | Null>

                        # used for question sequencing, when a question combes before or after another question
                        questionSequence: <Object | Null>
                            # next question reference
                            next: <DocumentReference<Question> | Null>

                            # previous question reference
                            prev: <DocumentReference<Question> | Null>

                        # image part of the question
                        image: <Object | Null>
                            # bucked storage path where the file is stored
                            path: <String>

                            # download url of the image
                            url: <String>

                            # width of the image
                            width: <Number>

                            # heigh of the image
                            height: <Number>

                        # array with all the options for this question
                        answers: <Array<Object>>
                            0:
                                # main text of this answer
                                answerText: <String>

                                # wether this answer is correct or not
                                correct: <Boolean>

                                # message in case this answer is selected
                                answerMessage: <String | Null>

                        # stats of this question
                        questionStats: <Object>
                            # number of times this question has been answered
                            timesAnswered: <Number>

                            # number of times this question was answered correctly on first try
                            correctFirstTime: <Number>

                # =======================================================
                # Sub-collection of blockResponses / history
                # =======================================================
                Collection: BlockResponses
                    {blockResponse Document}
                        # identifier of the response
                        id: <String>

                        # reference to the user document
                        userReference: <DocumentReference<User>>

                        # name of the user
                        name: <String>
                        
                        # avatar of the user
                        avatar: <Object>
                            # Web url of the image
                            url: <String> 
                            
                            # Path to the storage location, if a file was uploaded to the  storage bucket
                            path: <String | Null>

                            # Width of the image, if provided
                            width: <Number | Null>

                            # Heigh of the image, if provided
                            heigh: <Number | Null>

                        # points this user obtained in this blockResponse
                        pointsObtained: <Number>

                        # reference to the game played with the history, and selections
                        gamePlayedReference: <DocumentReference<GamePlayed>>
                        
                        # date when the user user played this block.
                        date: <Date>
```

#### Question difficulty

The assignable values for difficulty are EASY, MEDIUM, or HARD. The difficulty is also used to calculate the final punctuation of the user.

```yaml
QuestionDifficulty:
  EASY: 'EASY'
  MEDIUM: 'MEDIUM'
  HARD: 'HARD'
```

### Power Ups

```yaml
Collection: Power Ups
    {Porwer Up Document}
        # Archievement identifier
        id: <String>
        
        # Name of the archievement
        name: <String>
        
        # Description of this archievement
        description: <String>
        
        # Cost of this power up
        coins: <String>
        
        # Times this power up can be used
        uses: <String>
```

### Users

All the information stored in the **User Document** is private by default, and its only used to keep track of the claims, roles, subscriptions, data, and private information

```yaml
Collection: Users
    {User Document}
        # uid generated by firebase authentication
        uid: "g-asdfasdfasdfasdf"

        # display name of the user, given by firebase authentication
        name: "Bruno Alexander Esparza Carchi"

        # global points this user has earned
        points: <Number>

        # number of games this user has played
        playedGames: <Number>
        
        # global ranking of the user
        globalRanking: <Number>

        # date when the user joined
        joinDate: <Date>

        # date of the last session of the user
        lastSession: <Date>
        
        # avatar of the user
        avatar: <Object>
            # Web url of the image
            url: <String> 

            # Path to the storage location, if a file was uploaded to the  storage bucket
            path: <String | Null>

            # Width of the image, if provided
            width: <Number | Null>

            # Heigh of the image, if provided
            heigh: <Number | Null>
        
        # achievements this user has
        achievements: <Array<Object>>
            0:
                # name of the achievement
                name: <String>
                
                # reference to the achievement
                reference: <DocumentReference<Achievement>>
                
        # friends of this user
        friends: <Array<Object>>
            0:
                # reference to the user/friend
                reference: <DocumentReference<User>>
                
                # name of the friend
                name: <String>
                
                # Avatar of the friend
                avatar: <object>
                    # Web url of the image
                    url: <String> 

                    # Path to the storage location, if a file was uploaded to the  storage bucket
                    path: <String | Null>

                    # Width of the image, if provided
                    width: <Number | Null>

                    # Heigh of the image, if provided
                    heigh: <Number | Null>
                    
        # =======================================================
        # account configuration sub-collection
        # =======================================================
        Collection: AccountConfiguration
            # user claims, document synchronized to the user custom claims
            Document: Claims
                # boolean whether this user is an admin or not
                isAdmin: False

                # the subscription this user has
                subscription: <Subscription>

            # store keys, and protected data of the user, notications, payment information
            Document: Protected
                # key ot the device to send notifications
                notificationKey: "adsfasdf.qwerqwerqw.asdf"

            # user subscription information
            Document: Inscription
                # the preferred or fist selection of the user
                selectedDegrees: <Array<Object>>
                    0:
                        # reference to the academic degree
                        reference: <DocumentReference<AcademicDegree>>

                        # name of the academic degree
                        name: "Administración de empresas"

                # Knowledge areas included by the degrees selections
                knowledgeAreas: <Array<Object>>
                    0:
                        # Firestore reference to that knowledge Area
                        reference: <DocumentReference<KnowledgeArea>>

                        # raw id of the Knowledge area
                        id: "comprencion-lectora"

                        # display name of the knowledge area
                        name: "Comprensión lectora",

                        # specific style, and decorations of this Knowledge area
                        style: <Object>
                            # background color in hexadecimal format
                            bgColor: "#fe340f"

        # =======================================================
        # Games played sub-collection, blocks taken, and questions answered, all history
        # =======================================================
        Collection: GamesPlayed
            {GamePlayed Document}
                # identifier of the game played
                id: <String>

                # points earned on this game
                pointsObtained: 35

                # time in minuted the user took the test
                time: 10
                
                # date when the game was played
                date: <Date>
                
                # question block played
                questionBlock: <Object>
                    # reference to the original question block
                    reference: <DocumentReference<QuestionsBlock>>

                    # Name of the question block
                    name: <String | Null>

                # question answered by the user in this game
                questions: <Array<Objects>>
                    0:
                        # reference to the played game
                        reference: <DocumentReference<Question>>

                        # value of the question in points
                        points: 2

                        # text of the question
                        questionText: "Cual es el ..."

                        # text of the correct answer
                        correctAnswerText: "La respuesta es ..."

                        # attempts before selecting the correct one
                        attempts: 3
        # =======================================================
        # Friends Activitie sub-collection
        # =======================================================
        Collection: Friends Activity
            {Friend Activity Document}
                # identifier of the response
                id: <String>

                # reference to the user document
                userReference: <DocumentReference<User>>

                # name of the user
                name: <String>

                # avatar of the user
                avatar: <Object>
                    # Web url of the image
                    url: <String> 

                    # Path to the storage location, if a file was uploaded to the  storage bucket
                    path: <String | Null>

                    # Width of the image, if provided
                    width: <Number | Null>

                    # Heigh of the image, if provided
                    heigh: <Number | Null>

                # points this user obtained in this blockResponse
                pointsObtained: <Number>

                # reference to the game played with the history, and selections
                gamePlayedReference: <DocumentReference<GamePlayed>>

                # date when the user user played this block.
                date: <Date>
```

#### Subscription

Level of subscription this user has.

```yaml
Subscription:
  NONE: 'NONE'
  BASIC: 'BASIC'
  EXPERT: 'EXPERT'
```

## Realtime Database

### Multiplayer Game Example

```json
{
    "multiplayer": {
        "9846513289746": {
            "status": "STARTING",
            "status": "FINISHED",
            "status": "STORE",
            "status": "QUESTIONS",
            "currentQuestion": 1,
            "users": {
                "g-asdfweq987qw5215wqe": {
                    "id": "g-asdfweq987qw5215wqe",
                    "name": "Jonathan Andres Rosero Soto",
                    "avatar": null,
                    "points": 1500,
                    "coins": 1000,
                    "power-ups": {
                        "rayo": {
                            "id": "rayo",
                            "name": "Rayo",
                            "count": 2
                        }
                    },
                    "correctCounter": 3,
                    "currentQuestion": 1,
                    "effect": {
                        "mochuelo": {
                            "id": "mochuelo",
                            "name": "Mochuelo",
                            "uses": 1
                        }
                    }
                },
                "g-aqrewjnosladaf9821": {
                    "id": "g-aqrewjnosladaf9821",
                    "name": "Bruno Alexander Esparza Carchi",
                    "avatar": null,
                    "points": 1400,
                    "coins": 1000,
                    "power-ups": {
                        "rayo": {
                            "id": "rayo",
                            "name": "Rayo",
                            "count": 1
                        }
                    },
                    "correctCounter": 2,
                    "currentQuestion": 3,
                    "effect": {
                        "rayo": {
                            "id": "rayo",
                            "name": "Rayo",
                            "uses": 1
                        }
                    }
                }
            },
            "questions": {
                "0": {
                    "questionText": "Cual es el lenguaje de programación que se utiliza en los navegadores web?",
                    "id": "qb5daveW8ba8EYovn3Mw",
                    "time": 15,
                    "defaultWrongAnswerMessage": "Respuesta incorrecta, te recomiendo html for dummy's",
                    "difficulty": "HARD",
                    "image": null,
                    "answers": {
                        "0": {
                            "answerText": "Javascript",
                            "correct": true
                        },
                        "1": {
                            "answerText": "HTML",
                            "correct": false,
                            "answerMessage": "HTML no es un lenguaje de programación, es un lenguaje de maquetado"
                        }
                    },
                    "status": {
                        "g-asdfweq987qw5215wqe": "COMPLETED",
                        "g-asdfweq987qw5215wqe": "UNCOMPLETED",
                        "g-aqrewjnosladaf9821": "WAITING"
                    }
                }
            },
            "power-ups": {
                "rayo": {
                    "id": "rayo",
                    "name": "Rayo",
                    "description": "Lorem ipsum dolor sit amet consectetur ...",
                    "coins": 300
                }
            }
        }
    }
}
```
